/* gamescom 2026 guide — the few things the guide and the hall map must
   agree on, byte for byte.

   Two pages now read and write the same saved/played lists and answer
   the same question about the same booth. Anything they each kept their
   own copy of would drift silently: a different `gameKey` normalisation
   would strand game marks made on the other page, and a different booth
   code normalisation would light up the wrong stand. So the storage
   shape, the "is this saved" predicate and the booth-code normaliser
   live here, and nothing else does — this is not a utility drawer.

   Loaded as a plain script before js/app.js and js/map.js (no build
   step, same as the rest of the guide) and used through the GCMarks
   global.

   `data/hallplan/*.json` is generated by tools/fetch-hallplan.mjs, which
   is Node and cannot load this file; boothCodes() is mirrored there as
   codeSet(). If you change one, change the other — the tool's join
   report will tell you loudly if they disagree. */

const GCMarks = (() => {
  const MARK_KEYS = { saved: "gc2026.saved.v1", played: "gc2026.played.v1" };
  const PREFS_KEY = "gc2026.prefs.v1";

  /* Trade exhibitors, the three facts both pages must agree on.

     A booth in the business halls has no card of its own, so it is saved
     under its directory slug. If the map minted a different key shape than
     the guide reads, a booth saved on one would be invisible on the other —
     the same class of silent drift boothCodes() is here to prevent. And
     which halls *are* the business area decides which rows get a key at
     all, so that predicate is shared too rather than written twice.

     Halls 2-4, per gamescom's own "business area/halls 2-4". Hall 1 is the
     public Event Arena, and parseFloat leaves the open-air "F8"/"FI" sites
     as NaN, which fails both comparisons. */
  const DIR_PREFIX = "dir:";
  const dirKey = (slug) => DIR_PREFIX + slug;
  const isDirKey = (key) => typeof key === "string" && key.startsWith(DIR_PREFIX);
  const dirSlug = (key) => String(key).slice(DIR_PREFIX.length);
  const isBusinessHall = (hall) => {
    const level = parseFloat(hall);
    return level >= 2 && level < 5;
  };

  /* Read-only here: the guide owns writing prefs. The map only needs to know
     whether trade mode is on, so it never has to guess at the blob's shape. */
  function tradeMode() {
    try {
      return JSON.parse(localStorage.getItem(PREFS_KEY) || "{}").trade === true;
    } catch {
      return false;
    }
  }

  /* Read-modify-write, never a bare `{trade: on}`: the guide keeps its filter
     and section state in the same blob and writes it whole from memory, so a
     switch thrown on the map must hand the rest back untouched. The guide's
     own storage listener picks the change up; this tab gets no storage event
     for its own write and has to redraw itself. */
  function setTradeMode(on) {
    let prefs = {};
    try {
      const raw = JSON.parse(localStorage.getItem(PREFS_KEY) || "{}");
      if (raw && typeof raw === "object") prefs = raw;
    } catch {
      /* corrupt entry — replaced below, same as the guide's loadPrefs() */
    }
    prefs.trade = on === true;
    try {
      localStorage.setItem(PREFS_KEY, JSON.stringify(prefs));
    } catch {
      /* storage blocked (Safari private mode): the switch does not stick,
         which is the same deal every other preference on this site gets */
    }
  }

  /* Games are keyed by normalised title, not by booth: eight titles this
     year are shown at two booths at once (Alien: Isolation 2 sits at
     both Xbox and SEGA), and a mark applies to the game everywhere. */
  const gameKey = (title) => String(title).trim().toLowerCase().replace(/\s+/g, " ");

  function readMarks(mark) {
    try {
      const raw = JSON.parse(localStorage.getItem(MARK_KEYS[mark]) || "{}");
      return {
        exhibitors: new Set(Array.isArray(raw.exhibitors) ? raw.exhibitors : []),
        games: new Set(Array.isArray(raw.games) ? raw.games : []),
      };
    } catch {
      /* corrupt entry, or storage blocked entirely (Safari private mode) */
      return { exhibitors: new Set(), games: new Set() };
    }
  }

  function writeMarks(mark, marks) {
    try {
      localStorage.setItem(
        MARK_KEYS[mark],
        JSON.stringify({ exhibitors: [...marks.exhibitors], games: [...marks.games] })
      );
    } catch {
      /* out of quota or storage denied — marks still work for this session */
    }
  }

  const savedGames = (marks, ex) =>
    (ex.games || []).filter((g) => marks.games.has(gameKey(g.title)));

  /* An exhibitor counts as saved if you saved the booth itself *or* any
     game they're showing — the publisher is how you actually get to the
     game. The map colours stands by this, the guide filters by it. */
  const hasSaved = (marks, ex) =>
    marks.exhibitors.has(ex.id) || savedGames(marks, ex).length > 0;

  /* Booth codes, from either side, reduced to a comparable set:
     the guide writes "A061/C060", Koelnmesse files "A-061 C-060", and
     both mean the same two stands.

     The separator is not always there. The official directory files a few
     shared booths as "F040gE057g" — two codes run together — so each part
     is also scanned for letter+digits runs, and only falls back to
     stripping punctuation when it holds none (that keeps hyphenated
     "A-061" and non-code text such as "Freifläche" reading as they did). */
  const boothCodes = (str) =>
    new Set(
      String(str || "")
        .split(/[\s/,+]+/)
        .flatMap((part) => part.match(/[A-Za-z]\d+[a-z]?/g) || [part.replace(/[^0-9a-z]/gi, "")])
        .map((code) => code.toUpperCase())
        .filter(Boolean)
    );

  return {
    MARK_KEYS, PREFS_KEY, gameKey, readMarks, writeMarks, savedGames, hasSaved, boothCodes,
    DIR_PREFIX, dirKey, isDirKey, dirSlug, isBusinessHall, tradeMode, setTradeMode,
  };
})();
