/* gamescom 2026 guide — the few things the guide and the hall map must
   agree on, byte for byte.

   Two pages now read and write the same saved/played lists and answer
   the same question about the same booth. Anything they each kept their
   own copy of would drift silently: a different `gameKey` normalisation
   would strand game marks made on the other page, and a different booth
   code normalisation would light up the wrong stand. So the storage
   shape, the "is this saved" predicate and the booth-code normaliser
   live here, and nothing else does — this is not a utility drawer.

   Loaded as a plain script before js/app.js and js/map.js (no build
   step, same as the rest of the guide) and used through the GCMarks
   global.

   `data/hallplan/*.json` is generated by tools/fetch-hallplan.mjs, which
   is Node and cannot load this file; boothCodes() is mirrored there as
   codeSet(). If you change one, change the other — the tool's join
   report will tell you loudly if they disagree. */

const GCMarks = (() => {
  const MARK_KEYS = { saved: "gc2026.saved.v1", played: "gc2026.played.v1" };

  /* Games are keyed by normalised title, not by booth: eight titles this
     year are shown at two booths at once (Alien: Isolation 2 sits at
     both Xbox and SEGA), and a mark applies to the game everywhere. */
  const gameKey = (title) => String(title).trim().toLowerCase().replace(/\s+/g, " ");

  function readMarks(mark) {
    try {
      const raw = JSON.parse(localStorage.getItem(MARK_KEYS[mark]) || "{}");
      return {
        exhibitors: new Set(Array.isArray(raw.exhibitors) ? raw.exhibitors : []),
        games: new Set(Array.isArray(raw.games) ? raw.games : []),
      };
    } catch {
      /* corrupt entry, or storage blocked entirely (Safari private mode) */
      return { exhibitors: new Set(), games: new Set() };
    }
  }

  function writeMarks(mark, marks) {
    try {
      localStorage.setItem(
        MARK_KEYS[mark],
        JSON.stringify({ exhibitors: [...marks.exhibitors], games: [...marks.games] })
      );
    } catch {
      /* out of quota or storage denied — marks still work for this session */
    }
  }

  const savedGames = (marks, ex) =>
    (ex.games || []).filter((g) => marks.games.has(gameKey(g.title)));

  /* An exhibitor counts as saved if you saved the booth itself *or* any
     game they're showing — the publisher is how you actually get to the
     game. The map colours stands by this, the guide filters by it. */
  const hasSaved = (marks, ex) =>
    marks.exhibitors.has(ex.id) || savedGames(marks, ex).length > 0;

  /* Booth codes, from either side, reduced to a comparable set:
     the guide writes "A061/C060", Koelnmesse files "A-061 C-060", and
     both mean the same two stands. */
  const boothCodes = (str) =>
    new Set(
      String(str || "")
        .split(/[\s/,+]+/)
        .map((code) => code.replace(/[^0-9a-z]/gi, "").toUpperCase())
        .filter(Boolean)
    );

  return { MARK_KEYS, gameKey, readMarks, writeMarks, savedGames, hasSaved, boothCodes };
})();
