import { describe, expect, it } from "vitest";

import directory from "../data/directory.json";

/* data/directory.json is generated by tools/fetch-directory.py against two
   different sites, so what is worth asserting here is not its contents — those
   change every refresh — but the invariants a bad sweep would break quietly.
   A `brand` that went wrong does not throw: it puts a stranger's name on a
   booth, or buries the field's usefulness under 1,700 copies of `name`. */

const rows = directory.exhibitors;
const branded = rows.filter((row) => "brand" in row);

/* Mirror of directoryMatches() in js/app.js: the query is lowercased, split on
   whitespace, and every term has to appear somewhere in the row's haystack. */
const findableBy = (query, row) => {
  const haystack = `${row.name} ${row.country || ""}`.toLowerCase();
  return query
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean)
    .every((term) => haystack.includes(term));
};

describe("directory rows", () => {
  it("carries the fields the Full directory renders", () => {
    expect(rows.length).toBeGreaterThan(0);
    expect(rows.length).toBe(directory.count);
    for (const row of rows) {
      expect(typeof row.name).toBe("string");
      expect(row.name.trim()).not.toBe("");
      expect(typeof row.slug).toBe("string");
      expect(row.slug.trim()).not.toBe("");
    }
  });

  it("gives every row a unique slug, because that is its saved identity", () => {
    const slugs = rows.map((row) => row.slug);
    expect(new Set(slugs).size).toBe(slugs.length);
  });
});

describe("brand names", () => {
  it("finds the brands that hide behind a legal entity", () => {
    /* The case this field exists for: gamescom's own profile page is titled
       "Pipapo Games", and nothing about the row it is registered under says
       so. If a refresh ever drops this the search regresses silently. */
    const pipapo = rows.find((row) => row.brand === "Pipapo Games");
    expect(pipapo, "no row is branded Pipapo Games").toBeDefined();
    expect(pipapo.name).toMatch(/Hantschel/);
    expect(findableBy("Pipapo Games", pipapo)).toBe(false);
    expect(branded.length).toBeGreaterThan(10);
  });

  it("writes a brand only where search could not already find the row", () => {
    /* The whole value of the field is that it is small and every entry earns
       its place. A sweep that started copying `name` into `brand` would still
       parse, still render, and quietly double the file. */
    const redundant = branded.filter((row) => findableBy(row.brand, row));
    expect(redundant.map((row) => `${row.brand} <- ${row.name}`)).toEqual([]);
    expect(branded.length).toBeLessThan(rows.length / 10);
  });

  it("keeps every brand a usable, distinct name", () => {
    for (const row of branded) {
      expect(typeof row.brand).toBe("string");
      expect(row.brand.trim()).toBe(row.brand);
      expect(row.brand).not.toBe("");
      expect(row.brand).not.toBe(row.name);
    }
  });

  it("lets no two rows claim the same brand", () => {
    /* Two rows reading "Deep Silver" would send a visitor to whichever they
       happened to tap. The sweep drops a contested brand rather than picking;
       this is that promise, checked against what shipped. */
    const seen = new Map();
    for (const row of branded) {
      const key = row.brand.toLowerCase();
      expect(seen.has(key), `${row.brand} claimed twice`).toBe(false);
      seen.set(key, row.slug);
    }
  });
});
