#!/usr/bin/env node
/* Write dist/sitemap.xml.
 *
 *   node tools/make-sitemap.mjs            after tools/build-site.sh has staged dist/
 *
 * Generated at deploy time rather than committed, so there is no copy in the
 * repo to fall behind the pages it describes.
 *
 * The URL set is not written here. It is read back out of the staged pages,
 * from the <link rel="alternate" hreflang> block each one carries — those
 * links are what a search engine actually acts on, so rather than keep a
 * second list in step with them, this derives from them and a page whose
 * alternates change brings the sitemap along with it. A listed page without
 * alternates is an error, not an omission: it would mean the German edition
 * of that page had quietly stopped being reachable.
 *
 * lastmod is data/meta.json's lastUpdated — the date the exhibitor data was
 * last revised, which is the only thing about these pages that moves. Not
 * lastChecked, which moves every refresh: a daily lastmod on pages that did
 * not change is a crawl budget spent on nothing. Node ≥18, no dependencies.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dist = join(root, "dist");

/* imprint.html and privacy.html are deliberately absent: both carry
   <meta name="robots" content="noindex">, and a sitemap is a request to
   index. Listing them would be the site contradicting itself. */
const PAGES = ["index.html", "map.html"];

const ALTERNATE = /<link\s+rel="alternate"\s+hreflang="([^"]+)"\s+href="([^"]+)"\s*\/?>/g;

const xml = (s) =>
  String(s).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&apos;" }[c])
  );

const { lastUpdated } = JSON.parse(readFileSync(join(root, "data", "meta.json"), "utf8"));
if (!/^\d{4}-\d{2}-\d{2}$/.test(lastUpdated || "")) {
  console.error(`make-sitemap: data/meta.json lastUpdated is not a date: ${lastUpdated}`);
  process.exit(1);
}

const entries = [];
for (const page of PAGES) {
  const html = readFileSync(join(dist, page), "utf8");
  const alternates = [...html.matchAll(ALTERNATE)].map(([, hreflang, href]) => ({ hreflang, href }));
  if (!alternates.length) {
    console.error(`make-sitemap: ${page} carries no <link rel="alternate" hreflang> — see index.html`);
    process.exit(1);
  }

  /* One <url> per language variant, each repeating the whole alternate set:
     that reciprocity is what makes the annotation valid. x-default names the
     same address as en, so the locs are deduped — the same URL twice in one
     sitemap is a warning in every validator that reads it. */
  const locs = [...new Set(alternates.map((a) => a.href))];
  for (const loc of locs) {
    entries.push(
      [
        "  <url>",
        `    <loc>${xml(loc)}</loc>`,
        `    <lastmod>${lastUpdated}</lastmod>`,
        ...alternates.map(
          (a) => `    <xhtml:link rel="alternate" hreflang="${xml(a.hreflang)}" href="${xml(a.href)}"/>`
        ),
        "  </url>",
      ].join("\n")
    );
  }
}

const doc = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!-- Generated by tools/make-sitemap.mjs from the hreflang links in the pages themselves. -->',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
  '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  ...entries,
  "</urlset>",
  "",
].join("\n");

writeFileSync(join(dist, "sitemap.xml"), doc);
console.log(`make-sitemap: wrote dist/sitemap.xml — ${entries.length} URLs, lastmod ${lastUpdated}`);
